health_care_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sign/', include('userauth.urls')),
    url(r'^query/', include('query.urls')),
    url(r'^stories/', include('scrapedstories.urls')),
    url(r'^share/', include('share.urls')),

]

query/urls.py
from django.conf.urls import url
from . import views

app_name = 'query'
urlpatterns = [
    url(r'^$', views.queryhome, name='queryhome'),
    url(r'^post/$', views.postquery, name='postquery'),
    url(r'^solution(?P<question_id>[0-9]+)/$', views.solution, name='solution'),
    url(r'^upvote(?P<soln_id>[0-9]+)/$', views.upvote, name='upvote'),
    url(r'^downvote(?P<soln_id>[0-9]+)/$', views.downvote, name='downvote'),
    #url(r'^post/$', views.query, name='postquery'),
    #url(r'^$', views.query, name='querypage'),
    #url(r'home^$', views.query, name='querypage'),


]

scrapedstories/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name='scrapedstories'
urlpatterns = [

    url(r'^$', views.scraperpopulate, name='scraperpopulate'),
    url(r'^mystory/$', views.mystory, name='mystory'),

]

share/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .import views
app_name='share'
urlpatterns = [
    url(r'^$', views.share,name='share'),
    url(r'^upvote(?P<soln_id>[0-9]+)/$', views.upvote, name='upvote'),
    url(r'^downvote(?P<soln_id>[0-9]+)/$', views.downvote, name='downvote'),


]

userauth/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views


app_name='userauth'
urlpatterns = [
    url(r'^in$', views.signin, name='login'),
    url(r'^up(?P<status>[A-z]*?)/$', views.signup, name='signup'),
    url(r'^out$', views.signout, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile(?P<user_id>[0-9]+)/$', views.fetchprofile, name='profile'),

]

share/models.py
from django.db import models
from django.conf import settings
from userauth.models import Doctor

# Create your models here.
class Experience(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField(null=True, blank =True)
    time = models.DateTimeField(null=True, blank =True)
    sentiment = models.CharField(max_length=50,null=True, blank =True,default='neutral')

class Sclassifier(models.Model):
    experience = models.ForeignKey(Experience, on_delete=models.CASCADE)
    tag = models.CharField(max_length=50,null=True, blank =True)
    i_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,blank=True,null=True)
    d_id = models.ForeignKey(Doctor,models.CASCADE,)

class Templog(models.Model):
    experience = models.OneToOneField(Experience, on_delete=models.CASCADE)
    doctor = models.CharField(max_length=50,null=True, blank =True)
    institution = models.CharField(max_length=50,null=True, blank =True)
    place = models.CharField(max_length=50,null=True, blank =True)
    regno = models.IntegerField(null=True, blank =True,default=0)

share/forms.py
from django import forms

class ShareForm(forms.Form):
      text = forms.CharField(max_length=1220,widget= forms.Textarea({ "placeholder": "Write your experience..","required":"True","class":"form-control","rows":6,"cols":160}))
      doctor = forms.CharField(required=False,max_length=220,widget= forms.TextInput({ "placeholder": "Specify doctor if any..","class":"form-control","rows":6,"cols":160}))
      regno = forms.IntegerField(required=False,widget= forms.TextInput({ "default":0,"placeholder": "Specify register number of doctor..","class":"form-control","rows":6,"cols":160}))
      place = forms.CharField(required=False,max_length=220,widget= forms.TextInput({ "placeholder": "Specify the place..","class":"form-control","rows":6,"cols":160}))
      institution = forms.CharField(required=False,max_length=220,widget= forms.TextInput({ "placeholder": "Specify Institution if any...","class":"form-control","rows":6,"cols":160}))

share/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render
from django.db.models import Q

from share.forms import ShareForm
from .models import Experience, Templog
from django.utils import timezone
from sentianalyzer import analyzesentiment
# Create your views here.
@login_required
def share(request):
    if request.method=="POST":
      form = ShareForm(request.POST)
      if form.is_valid():
         a=Experience()
         a.text=request.POST['text']
         a.sentiment = analyzesentiment(request.POST['text'])
         a.time = timezone.now()
         a.user=request.user
         a.save()
         b=Templog()
         b.experience=a

         b.doctor = request.POST['doctor']

         b.institution = request.POST['institution']

         b.place = request.POST['place']

         b.regno=form.cleaned_data['regno']
         b.save()

         #code for furthur retrieval of similar
         '''exp=Experience.objects.exclude(user = request.user)
         for ex in exp:
             log=Templog.objects.get(experience = ex).'''
         log = Templog.objects.exclude(experience__user=request.user)
         flog = log.filter(Q(doctor = request.POST['doctor'])|Q(institution = request.POST['institution'])|Q(place = request.POST['place'])|Q(regno = form.cleaned_data['regno']))

         return render(request, 'share/share.html', {'form': form,'logs':flog})

    else:
         form = ShareForm()
         return render(request,'share/share.html',{'form':form})



    '''Poll.objects.get(
    Q(question__startswith='Who'),
    Q(pub_date=date(2005, 5, 2)) | Q(pub_date=date(2005, 5, 6))
)'''
def upvote():
    pass

def downvote():
    pass

share/templates/share/share.html
{%load staticfiles%}
<!DOCTYPE html>
<html lang="en">
  <head>


    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">

    <title>i-Care!</title>
  <link rel="stylesheet" href="{%static 'query/ooo.css'%}" type="text/css">

<link href="{% static 'query/bootstrap.min.css'%}" rel="stylesheet">
<style>
html
{
height:100%;
box-sizing:border-box;
}
body{
        background-image: url("vv.jpg ");
    margin: 3;

postion:relative;

min-height:90%;
  }
 
</style>



</head><body>
<header>

<div class="branding-bar pa-bg">
<img alt="Bootstrap Image Preview" src="{%static 'query/images/med.jpg'%}" class="img-circle" width="60" height="60">

        <ul class="top-nav">
          <li><a href="#"><b>i-Care</a></li>
             
        </ul></div>
<div id="mobile-menu">
       <div class="topics" >
        <div class="scrollable">
         

 <ul class="topics-list">
            <li  class="active" >
              <a href="{%url 'scrapedstories:mystory'%}" >Stories</a>
            </li>
            <li class="flag pro-bg--before">
              <a href="{%url 'userauth:profile'%}" >Profile</a>
            </li>
            <li class="flag sha-bg--before">
              <a href="{%url 'share:share'%}" >Share</a>
            </li>
            <li class="flag qa-bg--before">
              <a href="{%url 'query:queryhome'%}" >Askit</a>
            </li>

          </ul>
          
        </div><!-- div.scrollable -->
        <a href="{%url 'userauth:logout'%}" class="sa">Logout</a>
      </div><!-- div.topics -->

    </div><!-- div.mobile-menu -->



</header>         


<br><br>

                        <div class="container-fluid">

<div class="form-horizontal">
<div class="form-group">

<div class="col-md-8">
<form action="{%url 'share:share'%}" method="post">
    {% csrf_token %}
    <div class="fieldWrapper">
        {{form.text.errors}}
        {{form.text}}
    </div>
    <div class="fieldWrapper">
        {{form.doctor.errors}}
        {{form.doctor}}
    </div>
    <div class="fieldWrapper">
        {{form.regno.errors}}
        {{form.regno}}
    </div>
    <div class="fieldWrapper">
        {{form.institution.errors}}
        {{form.institution}}
    </div>
     <div class="fieldWrapper">
        {{form.place.errors}}
        {{form.place}}
    </div>

<br>
<br>
      <input type="submit" value="Submit" class="btn btn-success" name="Let me Post!"/>
</form>
    <br>
</div>


</div>
    <!-- old share here....-->
     <div class="container-fluid">
        {% for log in logs %}
<div class="row">
		<div class="col-md-2"></div>

<div class="col-md-8">


<table class="table table-striped table-bordered"
 align="center" border="1">


<tr>

<td>
<p>Vote here!!</p>
<a href="{%url 'share:upvote' log.experience.id %}" class="btn btn-success">UpVote</a>
<br>
  <h2>  </h2>

  <br>

<a href="{%url 'share:downvote' log.experience.id %}" class="btn btn-success">DownVote</a>

</td>

<td>{{ log.experience.text }}</td>

</tr> <tr> <h5><span class="glyphicon glyphicon-time"></span> Post by {{log.experience.user.username}}</h5> </tr>
</table>
</div>
<div class="col-md-2"></div>
</div>
        {%endfor%}



</div>
</div>
</body>
</html>







