health_care_app/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^sign/', include('userauth.urls')),
    url(r'^query/', include('query.urls')),
    url(r'^stories/', include('scrapedstories.urls')),
    url(r'^share/', include('share.urls')),

]

query/urls.py
from django.conf.urls import url
from . import views

app_name = 'query'
urlpatterns = [
    url(r'^$', views.queryhome, name='queryhome'),
    url(r'^post/$', views.postquery, name='postquery'),
    url(r'^solution(?P<question_id>[0-9]+)/$', views.solution, name='solution'),
    url(r'^upvote(?P<soln_id>[0-9]+)/$', views.upvote, name='upvote'),
    url(r'^downvote(?P<soln_id>[0-9]+)/$', views.downvote, name='downvote'),
    #url(r'^post/$', views.query, name='postquery'),
    #url(r'^$', views.query, name='querypage'),
    #url(r'home^$', views.query, name='querypage'),


]

scrapedstories/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name='scrapedstories'
urlpatterns = [

    url(r'^$', views.scraperpopulate, name='scraperpopulate'),
    url(r'^mystory/$', views.mystory, name='mystory'),

]

share/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .import views
app_name='share'
urlpatterns = [
    url(r'^$', views.share,name='share'),
    url(r'^upvote(?P<soln_id>[0-9]+)/$', views.upvote, name='upvote'),
    url(r'^downvote(?P<soln_id>[0-9]+)/$', views.downvote, name='downvote'),


]

userauth/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views


app_name='userauth'
urlpatterns = [
    url(r'^in$', views.signin, name='login'),
    url(r'^up(?P<status>[A-z]*?)/$', views.signup, name='signup'),
    url(r'^out$', views.signout, name='logout'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^profile(?P<user_id>[0-9]+)/$', views.fetchprofile, name='profile'),

]

query/models.py
from django.db import models
from django.conf import settings


class Query(models.Model):
    user_posted = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    query_text = models.TextField(help_text='query here...')
    written = models.DateTimeField()
    disease = models.CharField(max_length=40,blank=True,null=True)
    soln_num = models.IntegerField(default = 0)

    def __str__(self):
        return self.query_text[:20]

class Solutions(models.Model):
    user_posted = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    query = models.ForeignKey(Query, on_delete=models.CASCADE )
    soln_text = models.TextField()
    soln_score = models.IntegerField(blank=True, null=True)
    written = models.DateTimeField()
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.soln_text[:30]


class Comments(models.Model):
    user_posted = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    soln = models.ForeignKey(Solutions, on_delete=models.CASCADE )
    comment_text = models.TextField()
    written = models.DateTimeField()

    def __str__(self):
        return self.comment_text

class Upvote(models.Model):
    solution = models.ForeignKey(Solutions, on_delete=models.CASCADE )
    voted_user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,)

class Downvote(models.Model):
    solution = models.ForeignKey(Solutions, on_delete=models.CASCADE )
    voted_user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

query/forms.py
from django import forms
from . models import Query
class PostQuery(forms.Form):
    query_text = forms.CharField(max_length=150,widget= forms.Textarea({ "placeholder": "Enter Your Questions here...","required":"True","class":"form-control","rows":'7',"cols":'150',"id":"question","width": "830px", "height": "158px"}))

    #style = "width: 830px; height: 158px;"

class PostSolutions(forms.Form):
    soln_text = forms.CharField(max_length=9500,widget= forms.Textarea({ "placeholder": "Enter Your answer here...","required":"True","class":"form-control","rows":'7',"cols":'150',"id":"question","width": "830px", "height": "158px"}))

query/views.py
from django.core.urlresolvers import reverse

from django.http import HttpResponseRedirect

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from query.forms import PostQuery, PostSolutions
from .models import Query, Solutions, Upvote,Downvote
from userauth.models import User
from userauth.models import Health_status
from django.utils import timezone
from django.http import HttpResponse
from scrapedstories import classifytext
# Create your views here.

@login_required
def postquery(request):
    if request.method == 'POST':
        form = PostQuery(request.POST)
        if form.is_valid():
            qi=Query()
            qi.query_text = form.cleaned_data['query_text']
            qi.user_posted = request.user
            qi.written = timezone.now()
            qi.disease = classifytext.classif(form.cleaned_data['query_text'])
            qi.save()
            queries = Query.objects.exclude(user_posted = request.user).filter(disease=qi.disease).order_by('?')[:5]
            myqueries = Query.objects.filter(user_posted=request.user)
            return render(request, 'query/qaa.html', {'queries': queries,'myqueries':myqueries})
        else:
            return HttpResponse("<p>Validation Error</p>")
    else:
        form = PostQuery()
        return render(request,'query/formm.html',{'form':form})

def queryhome(request):
    choice = Health_status.objects.get(user=request.user)
    queries = Query.objects.filter(disease= choice.disease).order_by('?')[:5]
    myqueries = Query.objects.filter(user_posted=request.user)
    return render(request,'query/qaa.html',{'queries':queries,'myqueries':myqueries})

def solution(request,question_id):
    if request.method == 'POST':
        form = PostSolutions(request.POST)
        if form.is_valid():
            qi=Solutions()
            qi.soln_text = form.cleaned_data['soln_text']
            qi.user_posted = request.user
            qi.written = timezone.now()
            qi.query = Query.objects.get(id=question_id)
            qi.save()
            return HttpResponseRedirect(reverse('query:queryhome'))
            #return render(request, 'query/ans.html', {'queries': queries})
        else:
            return HttpResponse("<p>Validation Error</p>")
    else:
        form = PostSolutions()
        squery = Query.objects.get(id=question_id)
        solutions = Solutions.objects.filter(query = squery).order_by('?')[:3]
        return render(request, 'query/ans.html', {'soln': solutions,'form':form,'q_id':question_id})

def upvote(request,soln_id):
  if request.method == 'POST':
    soln = Solutions.objects.get(id=soln_id)
    try:
        user=Upvote.objects.filter(solution=soln).get(voted_user = request.user)
        if user:
            return HttpResponse("<p>sorry you voted once!!!!..................</p>")
        else:
            x=User.objects.get(username = 'asd')
    except:

        soln.vote = soln.vote+1
        soln.save()
        s=Upvote()
        s.solution = soln
        s.voted_user=request.user
        s.save()

        return render(request, 'query/ansclick.html',{'solution': soln})

def downvote(request,soln_id):
  if request.method == 'POST':
    soln = Solutions.objects.get(id=soln_id)
    try:
        user = Downvote.objects.filter(solution=soln).get(voted_user=request.user)
        if user:
            return HttpResponse("<p>sorry you voted once!!!!..................</p>")
        else:
            x = User.objects.get(username='asd')
    except:

        soln.vote = soln.vote-1
        soln.save()
        s=Downvote()
        s.solution = soln
        s.voted_user=request.user
        s.save()
        return render(request,'query/ansclick.html' ,{'solution': soln})

query/templates/query/ans.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">


     <link rel="stylesheet" href="{%static 'query/ooo.css' %}" type="text/css">
     <link href="{% static 'query/bootstrap.min.css' %}" rel="stylesheet">

     <link rel="stylesheet" type="text/css" href="{%static 'query/search.css'%}">


    <title>i-Care!</title>





    <link href="{% static 'query/navbars.css'%}" rel="stylesheet">
<style>
html
{
height:100%;
box-sizing:border-box;
}
body{
        background-image: url("ee.jpg ");
    margin: 0;

postion:relative;

min-height:100%;
  } 
 
</style>



  </head>
  <body>
    <header>

<div class="branding-bar pa-bg">
<img alt="i-Care Preview" src="{%static 'query/images/med.jpg'%}" class="img-circle" width="60" height="60">

        <ul class="top-nav">
            <li><a href="#"><b>i-Care</b></a></li>

        </ul></div>
<div id="mobile-menu">
       <div class="topics" >
        <div class="scrollable">


          <ul class="topics-list">
            <li  class="active" >
              <a href="{%url 'scrapedstories:mystory'%}" >Stories</a>
            </li>
            <li class="flag pro-bg--before">
              <a href="{%url 'userauth:profile'%}" >Profile</a>
            </li>
            <li class="flag sha-bg--before">
              <a href="{%url 'share:share'%}" >Share</a>
            </li>
            <li class="flag qa-bg--before">
              <a href="{%url 'query:queryhome'%}" >Askit</a>
            </li>

          </ul>

        </div><!-- div.scrollable -->
        <a href="{% url 'userauth:logout'%}" class="sa">Logout</a>
      </div><!-- div.topics -->

    </div><!-- div.mobile-menu -->



</header>
    <div class="col-md-8">
  <form action="{% url 'query:solution' q_id%}" method="post">
      {% csrf_token %}
    <!--<div class="form-group">-->
      <!--<br><label for="question"> <b>Type your question here::  </b></label>-->
      <br/>
      <div class="fieldWrapper">
        {{form.soln_text.errors}}
        <!--<label for="{{form.query_text.id_query_text}}">User Name:</label>-->
      <br><label for="question"> <b>Type your answer here::  </b></label>
        {{form.soln_text}}
      <!--</div>-->

    </div>
    <!--<a href="#" class="btn btn-success"> Submit</a>-->
    <button type="submit" class="btn btn-success">Submit answer</button>
  </form>
</div>
    <div class="container-fluid">
        {% for solution in soln%}
<div class="row">
		<div class="col-md-2"></div>

<div class="col-md-8">


<table class="table table-striped table-bordered"
 align="center" border="1">

 
<tr>

<td>
<p>Vote here!!</p>
      <form action="{%url 'query:upvote' solution.id %}" method="post">
      {% csrf_token %}
        <button type="submit" class="btn btn-success">Upvote</button>
  </form>
<br>
  <h2> {{solution.vote}} </h2>

  <br>

 <form action="{%url 'query:downvote' solution.id %}" method="post">
      {% csrf_token %}
        <button type="submit" class="btn btn-success">Downvote</button>
  </form>

</td>

<td>{{solution.soln_text}}</td>

</tr> <tr> <h5><span class="glyphicon glyphicon-time"></span> Post by {{solution.user_posted.username}}, {{solution.written}}.</h5> </tr>
</table>
</div>
<div class="col-md-2"></div>
</div>
        {%endfor%}

<!--<div class="row">
		<div class="col-md-2"></div>

<div class="col-md-8">


<table class="table table-striped table-bordered"
 align="center" border="1">
<tr>

<td>
<p>Vote here!!</p>

<a href="#" class="btn btn-success">UpVote</a>
<br><br>

<a href="#" class="btn btn-success">DownVote</a>

</td>


<td> Answer</td>
</tr>
<tr> <h5><span class="glyphicon glyphicon-time"></span> Post by Jane Dane, Sep 27, 2015.</h5> </tr>
</table>
</div>
<div class="col-md-2"></div>
</div>

<div class="row">
		<div class="col-md-2"></div>

<div class="col-md-8">


<table class="table table-striped table-bordered"
 align="center" border="1">
<tr>

<td>
<p>Vote here!!</p>

<a href="#" class="btn btn-success">UpVote</a>
<br><br>

<a href="#" class="btn btn-success">DownVote</a>

</td>


<td> Answer</td>
</tr>

<tr> <h5><span class="glyphicon glyphicon-time"></span> Post by Jane Dane, Sep 27, 2015.</h5> </tr>
</table>
</div>
<div class="col-md-2"></div>
</div>-->

</div>


</body>
</html>

query/templates/query/ansclick.html
 {% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>i-Care!</title>



    <link href="{% static 'query/bootstrap.min.css'%}" rel="stylesheet">


    <link href="{% static 'query/navbars.css'%}" rel="stylesheet">
<style>
html
{
height:100%;
box-sizing:border-box;
}
body{
        background-image: url("ee.jpg ");
    margin: 0;

postion:relative;

min-height:100%;
  }

</style>



  </head>
  <body>

    <div class="container-fluid">

<div class="row">
		<div class="col-md-2"></div>

<div class="col-md-8">


<table class="table table-striped table-bordered"
 align="center" border="1">


<tr>

<td>
<p>Vote here!!</p>
      <form action="{%url 'query:upvote' solution.id %}" method="post">
      {% csrf_token %}
        <button type="submit" class="btn btn-success">Upvote</button>
  </form>
<br>
   <h2> {{solution.vote}} </h2>


    <br>

      <form action="{%url 'query:downvote' solution.id %}" method="post">
      {% csrf_token %}
        <button type="submit" class="btn btn-success">Downvote</button>
  </form>

</td>

<td>{{solution.soln_text}}</td>

</tr> <tr> <h5><span class="glyphicon glyphicon-time"></span> Post by {{solution.user_posted.username}}, {{solution.written}}.</h5> </tr>
</table>
</div>
<div class="col-md-2"></div>
</div>


<!--<div class="row">
		<div class="col-md-2"></div>

<div class="col-md-8">


<table class="table table-striped table-bordered"
 align="center" border="1">
<tr>

<td>
<p>Vote here!!</p>

<a href="#" class="btn btn-success">UpVote</a>
<br><br>

<a href="#" class="btn btn-success">DownVote</a>

</td>


<td> Answer</td>
</tr>
<tr> <h5><span class="glyphicon glyphicon-time"></span> Post by Jane Dane, Sep 27, 2015.</h5> </tr>
</table>
</div>
<div class="col-md-2"></div>
</div>

<div class="row">
		<div class="col-md-2"></div>

<div class="col-md-8">


<table class="table table-striped table-bordered"
 align="center" border="1">
<tr>

<td>
<p>Vote here!!</p>

<a href="#" class="btn btn-success">UpVote</a>
<br><br>

<a href="#" class="btn btn-success">DownVote</a>

</td>


<td> Answer</td>
</tr>

<tr> <h5><span class="glyphicon glyphicon-time"></span> Post by Jane Dane, Sep 27, 2015.</h5> </tr>
</table>
</div>
<div class="col-md-2"></div>
</div>-->

</div>


</body>
</html>

query/templates/query/formm.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
<title>i-Care</title><link href="{% static 'query/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'query/ooo.css' %}" type="text/css">

<link href="{% static 'query/bootstrap.min.css'%}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'query/search.css'%}">
     <link href="{% static 'query/navbars.css'%}" rel="stylesheet">
</head>

<body>
<header>

<div class="branding-bar pa-bg">
<img alt="i-Care Preview" src="{%static 'query/images/med.jpg'%}" class="img-circle" width="60" height="60">

        <ul class="top-nav">
          <li><a href="#"><b>i-Care</a></li>

        </ul></div>
<div id="mobile-menu">
       <div class="topics" >
        <div class="scrollable">


          <ul class="topics-list">
            <li  class="active" >
              <a href="{%url 'scrapedstories:mystory'%}" >Stories</a>
            </li>
            <li class="flag pro-bg--before">
              <a href="{%url 'userauth:profile'%}" >Profile</a>
            </li>
            <li class="flag sha-bg--before">
              <a href="{%url 'share:share'%}" >Share</a>
            </li>
            <li class="flag qa-bg--before">
              <a href="{%url 'query:queryhome'%}" >Askit</a>
            </li>

          </ul>

        </div><!-- div.scrollable -->
        <a href="{% url 'userauth:logout'%}" class="sa">Logout</a>
      </div><!-- div.topics -->

    </div><!-- div.mobile-menu -->



</header>
<div class="col-md-8">
  <form action="{% url 'query:postquery'%}" method="post">
      {% csrf_token %}
    <!--<div class="form-group">-->
      <!--<br><label for="question"> <b>Type your question here::  </b></label>-->
      <br/>
      <div class="fieldWrapper">
        {{form.query_text.errors}}
        <!--<label for="{{form.query_text.id_query_text}}">User Name:</label>-->
      <br><label for="question"> <b>Type your question here::  </b></label>
        {{form.query_text}}
      <!--</div>-->

    </div>
    <!--<a href="#" class="btn btn-success"> Submit</a>-->
    <button type="submit" class="btn btn-success">log my question.</button>
  </form>
</div>
</body>
</html>
<!--btn btn-primary btn-block btn-large-->

query/templates/query/qaa.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700" type="text/css">

    <title>i-Care!</title>



  <link rel="stylesheet" href="{% static 'query/ooo.css' %}" type="text/css">

<link href="{% static 'query/bootstrap.min.css'%}" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="{% static 'query/search.css'%}">
<style>
html
{
height:100%;
box-sizing:border-box;
}
body{
        background-image: url("vv.jpg ");
    margin: 3;

postion:relative;

min-height:90%;
  }

</style>



</head>
<body>
<header>

<div class="branding-bar pa-bg">
<img alt="Bootstrap Image Preview" src="{%static 'query/images/med.jpg'%}" class="img-circle" width="60" height="60">

        <ul class="top-nav">
          <li><a href="#"><b>i-Care</a></li>

        </ul></div>
<div id="mobile-menu">
       <div class="topics" >
        <div class="scrollable">


           <ul class="topics-list">
            <li  class="active" >
              <a href="{%url 'scrapedstories:mystory'%}" >Stories</a>
            </li>
            <li class="flag pro-bg--before">
              <a href="{%url 'userauth:profile'%}" >Profile</a>
            </li>
            <li class="flag sha-bg--before">
              <a href="{%url 'share:share'%}" >Share</a>
            </li>
            <li class="flag qa-bg--before">
              <a href="{%url 'query:queryhome'%}" >Askit</a>
            </li>

          </ul>



        </div><!-- div.scrollable -->
        <a href="{%url 'userauth:logout'%}" class="sa">Logout</a>
      </div><!-- div.topics -->

    </div><!-- div.mobile-menu -->



</header>


<div class="container">

 <br><br>
   <div class="row">
    <div class="col-md-10">
     <section class="container">

   	   <form onsubmit="submitFn(this, event);">

           <div class="search-wrapper">

              <div class="input-holder">

                 <input type="text" class="search-input" placeholder="Type to search" />

                 <button class="search-icon" onclick="searchToggle(this, event);"><span></span></button>
              </div>

               <span class="close" onclick="searchToggle(this, event);"></span>
               <div class="result-container">
               </div>

           </div>
       </form>
	 </section>
	</div>
   </div>

  <div class="row">

    <div class="col-md-8">

        <br>
        <h7> <b>Recent Questions</b></h7>
        <br><br>
        {%for query in queries%}
        <table class="table table-striped table-bordered" border="0">
          <tr>

          <td>
            <a href="{% url 'query:solution' query.id %}">Question:{{forloop.counter}}-{{query.query_text}}</a>
          </td>

          </tr>
        </table>
        <table align="center">
        <tr>

           <h5><span class="glyphicon glyphicon-time"></span> Post by {{query.user_posted}}, {{query.written}}.</h5>

        </tr>
        </table>

        <br>
        {%endfor%}
        <br><br>
    </div>
        <div class="col-md-4">
		<a href="{% url 'query:postquery'%}" role="button" class="btn btn-primary"; ><b> Submit A Question!!</a>


		</div>
  </div>

        <h7> <b>My Questions</b></h7>
        <br><br>
        <table class="table table-striped table-bordered" border="0">
          <tr>

          <td>
           {%for query in myqueries%}
             {% if forloop.counter < 10 %}
                <a href="{% url 'query:solution' query.id %}">Question:{{forloop.counter}}-{{query.query_text}}</a>
                <br>
              {% endif %}
            {% endfor %}
          </td>
          </tr>
        </table>
    </div>

   <br><br>





 </div>
</div>
<footer>
<div class="container">

<div class="copyright f-left">
Copyright 2016|
<a href="#">By i-Care|</a>
<a href="#">Privacy</a>
</div>

</div>
</footer>

<script type="text/javascript" src="search.js"></script>

<script src="http://libs.useso.com/js/jquery/1.11.0/jquery.min.js" type="text/javascript"></script>
	<script>window.jQuery || document.write('<script src="js/jquery-1.11.0.min.js"><\/script>')</script>




    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/scripts.js"></script>
  </body>
</html>